server:
  port: 9002
spring:
  application:
    name: sms-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 127.0.0.1
aliyun:
  sms:
    accessKeyId: LTAIULJq0YmVBn6Q
    accessKeySecret: c3EjNBFqIbVePulRetOPjGIYBCKgHj
    template_code: SMS_187745070
    sign_name: 找房网-短信验证码