server:
  port: 9000 #端口号

spring:
  application:
    name: home-service #服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos注册地址
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false #不开启页面缓存
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
