spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: zxf18377217936
    url: jdbc:mysql://127.0.0.1:3306/searchroom?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false #不开启页面缓存
  redis:
    host: 127.0.0.1 # redis
  rabbitmq:
    host: 127.0.0.1 #rabbitMQ
  main:
    allow-bean-definition-overriding: true #多个Feign接口都指向一个服务
  servlet:
    multipart:
      max-file-size: 5MB # 设置单个文件上传大小为5MB
      max-request-size: 20MB # 总请求为20MB

server:
  port: 9001
mybatis:
  mapper-locations: classpath:mapper/*.xml #mybatis的mapper xml文件


token_name: token

redirectURL: http://192.168.1.100:10000/user-service/user/loginPage

jwt:
  config:
    key: searchroom #jwt言
    ttl: 3600000 #jwt过期时间
feign:
  sentinel:
    enabled: true #开启容错（服务降级，熔断）
  client:
    config:
      default:
        readTimeout: 60000 #Feign的请求处理超时时间，默认为60
        connectTimeout: 60000 #Feign的连接建立超时时间，默认为10秒
#        retryer: 5 #使用默认的超时配置，在该类源码中可见，默认单次请求最大时长1秒，重试5次

aliyunoos:
  config:
    endpoint: http://oss-cn-shanghai.aliyuncs.com
    accessKeyId: ****
    accessKeySecret: ****
    bucketName: searchroom
    objectName: images/
    url: https://searchroom.oss-cn-shanghai.aliyuncs.com/images/

# 日志配置的文件
#logging:
#  config:
#  file:
#    path: classpath:log #日志文件路径
#  level: debug #模式

