package com.zxf.dao;

import com.zxf.DO.HouseDetail;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@Mapper
public interface HouseDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_detail
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_detail
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int insert(HouseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_detail
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    HouseDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_detail
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    List<HouseDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_detail
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int updateByPrimaryKey(HouseDetail record);

    int insertHouseDetail(HouseDetail houseDetail);

    HouseDetail selectByHouseId(String id);

    int updateHouseDetail(HouseDetail houseDetail);
}