package com.zxf.dao;

import com.zxf.DO.HouseTag;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface HouseTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tag
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tag
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int insert(HouseTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tag
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    HouseTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tag
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    List<HouseTag> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_tag
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int updateByPrimaryKey(HouseTag record);

    int insertBatchHouseTags(List<HouseTag> houseTags);

    List<HouseTag> selectByHouseId(String id);

    int deleteTagByTagNameAndHouseId(@Param("id") String id, @Param("tag") String tag);
}