package com.zxf.dao;

import com.zxf.DO.HousePicture;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface HousePictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_picture
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_picture
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int insert(HousePicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_picture
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    HousePicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_picture
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    List<HousePicture> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_picture
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int updateByPrimaryKey(HousePicture record);

    int insertBatchHousePictures(List<HousePicture> housePictures);

    List<HousePicture> selectByHouseId(String id);
}