package com.zxf.dao;

import com.zxf.DO.House;
import com.zxf.DTO.HouseDTO;
import com.zxf.VO.HouseSearchVo;
import com.zxf.VO.RentHouseSearchVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;

@Repository
@Mapper
public interface HouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int insert(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    House selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    List<House> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int updateByPrimaryKey(House record);

    /**
     * 房源信息插入
     * @param house
     * @return
     */
    int insertHouse(House house);

    /**
     * 根据用户id查找房源
     * @param id
     * @return
     */
    List<House> selectHousesByAdmin(HouseSearchVo houseSearchVo);

    int updateHouse(House house);

    List<HouseDTO> selectHousesByUser(RentHouseSearchVo searchVo);

    int getRentHouseSum(@Param("cityEnName") String cityEnName, @RequestParam("regionEnName") String regionEnName,@Param("district") String district);

    List<HouseDTO> findHouseDTOS(@Param("ids")String ids);
}