package com.zxf.dao;

import com.zxf.DO.SubwayStation;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@Mapper
public interface SubwayStationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subway_station
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subway_station
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int insert(SubwayStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subway_station
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    SubwayStation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subway_station
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    List<SubwayStation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subway_station
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int updateByPrimaryKey(SubwayStation record);

    List<SubwayStation> selectBySubwayId(String subwayLineId);
}