package com.zxf.dao;

import com.zxf.DO.SupportAddress;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@Mapper
public interface SupportAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support_address
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support_address
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int insert(SupportAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support_address
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    SupportAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support_address
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    List<SupportAddress> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support_address
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    int updateByPrimaryKey(SupportAddress record);

    List<SupportAddress> selectSupportCities();

    List<SupportAddress> selectSupportRegionsBycityName(String cityName);

    SupportAddress selectSupportCity(String cityEnName);

    SupportAddress selectSupportRegion(@Param("cityEnName") String cityEnName,@Param("regionEnName") String regionEnName);
}