package com.zxf.DO;

import java.util.Date;

public class HouseSubscribe {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_subscribe.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_subscribe.house_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_subscribe.user_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_subscribe.desc
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_subscribe.status
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_subscribe.create_time
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_subscribe.last_update_time
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_subscribe.order_time
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_subscribe.telephone
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_subscribe.admin_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer adminId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_subscribe.id
     *
     * @return the value of house_subscribe.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_subscribe.id
     *
     * @param id the value for house_subscribe.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_subscribe.house_id
     *
     * @return the value of house_subscribe.house_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_subscribe.house_id
     *
     * @param houseId the value for house_subscribe.house_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_subscribe.user_id
     *
     * @return the value of house_subscribe.user_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_subscribe.user_id
     *
     * @param userId the value for house_subscribe.user_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_subscribe.desc
     *
     * @return the value of house_subscribe.desc
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_subscribe.desc
     *
     * @param desc the value for house_subscribe.desc
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_subscribe.status
     *
     * @return the value of house_subscribe.status
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_subscribe.status
     *
     * @param status the value for house_subscribe.status
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_subscribe.create_time
     *
     * @return the value of house_subscribe.create_time
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_subscribe.create_time
     *
     * @param createTime the value for house_subscribe.create_time
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_subscribe.last_update_time
     *
     * @return the value of house_subscribe.last_update_time
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_subscribe.last_update_time
     *
     * @param lastUpdateTime the value for house_subscribe.last_update_time
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_subscribe.order_time
     *
     * @return the value of house_subscribe.order_time
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_subscribe.order_time
     *
     * @param orderTime the value for house_subscribe.order_time
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_subscribe.telephone
     *
     * @return the value of house_subscribe.telephone
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_subscribe.telephone
     *
     * @param telephone the value for house_subscribe.telephone
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_subscribe.admin_id
     *
     * @return the value of house_subscribe.admin_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_subscribe.admin_id
     *
     * @param adminId the value for house_subscribe.admin_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
}