package com.zxf.DO;

import java.util.Date;

public class House {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.title
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.price
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.area
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.room
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer room;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.floor
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.total_floor
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer totalFloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.watch_times
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer watchTimes = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.build_year
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer buildYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.status
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer status = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.create_time
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.last_update_time
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.city_en_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String cityEnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.region_en_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String regionEnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.cover
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.direction
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.distance_to_subway
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer distanceToSubway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.parlour
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer parlour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.district
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.admin_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.bathroom
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer bathroom = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.street
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String street;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.id
     *
     * @return the value of house.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.id
     *
     * @param id the value for house.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.title
     *
     * @return the value of house.title
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.title
     *
     * @param title the value for house.title
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.price
     *
     * @return the value of house.price
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.price
     *
     * @param price the value for house.price
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.area
     *
     * @return the value of house.area
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.area
     *
     * @param area the value for house.area
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.room
     *
     * @return the value of house.room
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.room
     *
     * @param room the value for house.room
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setRoom(Integer room) {
        this.room = room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.floor
     *
     * @return the value of house.floor
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.floor
     *
     * @param floor the value for house.floor
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.total_floor
     *
     * @return the value of house.total_floor
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getTotalFloor() {
        return totalFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.total_floor
     *
     * @param totalFloor the value for house.total_floor
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setTotalFloor(Integer totalFloor) {
        this.totalFloor = totalFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.watch_times
     *
     * @return the value of house.watch_times
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getWatchTimes() {
        return watchTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.watch_times
     *
     * @param watchTimes the value for house.watch_times
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setWatchTimes(Integer watchTimes) {
        this.watchTimes = watchTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.build_year
     *
     * @return the value of house.build_year
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getBuildYear() {
        return buildYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.build_year
     *
     * @param buildYear the value for house.build_year
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setBuildYear(Integer buildYear) {
        this.buildYear = buildYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.status
     *
     * @return the value of house.status
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.status
     *
     * @param status the value for house.status
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.create_time
     *
     * @return the value of house.create_time
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.create_time
     *
     * @param createTime the value for house.create_time
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.last_update_time
     *
     * @return the value of house.last_update_time
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.last_update_time
     *
     * @param lastUpdateTime the value for house.last_update_time
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.city_en_name
     *
     * @return the value of house.city_en_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getCityEnName() {
        return cityEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.city_en_name
     *
     * @param cityEnName the value for house.city_en_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setCityEnName(String cityEnName) {
        this.cityEnName = cityEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.region_en_name
     *
     * @return the value of house.region_en_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getRegionEnName() {
        return regionEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.region_en_name
     *
     * @param regionEnName the value for house.region_en_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setRegionEnName(String regionEnName) {
        this.regionEnName = regionEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.cover
     *
     * @return the value of house.cover
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.cover
     *
     * @param cover the value for house.cover
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setCover(String cover) {
        this.cover = cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.direction
     *
     * @return the value of house.direction
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.direction
     *
     * @param direction the value for house.direction
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setDirection(Integer direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.distance_to_subway
     *
     * @return the value of house.distance_to_subway
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getDistanceToSubway() {
        return distanceToSubway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.distance_to_subway
     *
     * @param distanceToSubway the value for house.distance_to_subway
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setDistanceToSubway(Integer distanceToSubway) {
        this.distanceToSubway = distanceToSubway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.parlour
     *
     * @return the value of house.parlour
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getParlour() {
        return parlour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.parlour
     *
     * @param parlour the value for house.parlour
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setParlour(Integer parlour) {
        this.parlour = parlour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.district
     *
     * @return the value of house.district
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.district
     *
     * @param district the value for house.district
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.admin_id
     *
     * @return the value of house.admin_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.admin_id
     *
     * @param adminId the value for house.admin_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.bathroom
     *
     * @return the value of house.bathroom
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getBathroom() {
        return bathroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.bathroom
     *
     * @param bathroom the value for house.bathroom
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setBathroom(Integer bathroom) {
        this.bathroom = bathroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.street
     *
     * @return the value of house.street
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.street
     *
     * @param street the value for house.street
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setStreet(String street) {
        this.street = street;
    }
}