package com.zxf.DO;

public class HouseTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_tag.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_tag.house_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_tag.name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_tag.id
     *
     * @return the value of house_tag.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_tag.id
     *
     * @param id the value for house_tag.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_tag.house_id
     *
     * @return the value of house_tag.house_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_tag.house_id
     *
     * @param houseId the value for house_tag.house_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_tag.name
     *
     * @return the value of house_tag.name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_tag.name
     *
     * @param name the value for house_tag.name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}