package com.zxf.DO;

public class HousePicture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_picture.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_picture.house_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_picture.cdn_prefix
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String cdnPrefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_picture.width
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_picture.height
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_picture.location
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_picture.path
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_picture.id
     *
     * @return the value of house_picture.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_picture.id
     *
     * @param id the value for house_picture.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_picture.house_id
     *
     * @return the value of house_picture.house_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_picture.house_id
     *
     * @param houseId the value for house_picture.house_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_picture.cdn_prefix
     *
     * @return the value of house_picture.cdn_prefix
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getCdnPrefix() {
        return cdnPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_picture.cdn_prefix
     *
     * @param cdnPrefix the value for house_picture.cdn_prefix
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setCdnPrefix(String cdnPrefix) {
        this.cdnPrefix = cdnPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_picture.width
     *
     * @return the value of house_picture.width
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_picture.width
     *
     * @param width the value for house_picture.width
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_picture.height
     *
     * @return the value of house_picture.height
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_picture.height
     *
     * @param height the value for house_picture.height
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_picture.location
     *
     * @return the value of house_picture.location
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_picture.location
     *
     * @param location the value for house_picture.location
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_picture.path
     *
     * @return the value of house_picture.path
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_picture.path
     *
     * @param path the value for house_picture.path
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setPath(String path) {
        this.path = path;
    }
}