package com.zxf.DO;

public class HouseDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_detail.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_detail.description
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_detail.layout_desc
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String layoutDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_detail.traffic
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String traffic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_detail.round_service
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String roundService;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_detail.rent_way
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer rentWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_detail.address
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_detail.subway_line_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer subwayLineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_detail.subway_line_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String subwayLineName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_detail.subway_station_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer subwayStationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_detail.subway_station_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String subwayStationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_detail.house_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column support_address.baidu_map_lng
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Double baiduMapLng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column support_address.baidu_map_lat
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Double baiduMapLat;

    public Double getBaiduMapLng() {
        return baiduMapLng;
    }

    public void setBaiduMapLng(Double baiduMapLng) {
        this.baiduMapLng = baiduMapLng;
    }

    public Double getBaiduMapLat() {
        return baiduMapLat;
    }

    public void setBaiduMapLat(Double baiduMapLat) {
        this.baiduMapLat = baiduMapLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_detail.id
     *
     * @return the value of house_detail.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_detail.id
     *
     * @param id the value for house_detail.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_detail.description
     *
     * @return the value of house_detail.description
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_detail.description
     *
     * @param description the value for house_detail.description
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_detail.layout_desc
     *
     * @return the value of house_detail.layout_desc
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getLayoutDesc() {
        return layoutDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_detail.layout_desc
     *
     * @param layoutDesc the value for house_detail.layout_desc
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setLayoutDesc(String layoutDesc) {
        this.layoutDesc = layoutDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_detail.traffic
     *
     * @return the value of house_detail.traffic
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getTraffic() {
        return traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_detail.traffic
     *
     * @param traffic the value for house_detail.traffic
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setTraffic(String traffic) {
        this.traffic = traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_detail.round_service
     *
     * @return the value of house_detail.round_service
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getRoundService() {
        return roundService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_detail.round_service
     *
     * @param roundService the value for house_detail.round_service
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setRoundService(String roundService) {
        this.roundService = roundService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_detail.rent_way
     *
     * @return the value of house_detail.rent_way
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getRentWay() {
        return rentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_detail.rent_way
     *
     * @param rentWay the value for house_detail.rent_way
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setRentWay(Integer rentWay) {
        this.rentWay = rentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_detail.address
     *
     * @return the value of house_detail.address
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_detail.address
     *
     * @param address the value for house_detail.address
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_detail.subway_line_id
     *
     * @return the value of house_detail.subway_line_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getSubwayLineId() {
        return subwayLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_detail.subway_line_id
     *
     * @param subwayLineId the value for house_detail.subway_line_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setSubwayLineId(Integer subwayLineId) {
        this.subwayLineId = subwayLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_detail.subway_line_name
     *
     * @return the value of house_detail.subway_line_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getSubwayLineName() {
        return subwayLineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_detail.subway_line_name
     *
     * @param subwayLineName the value for house_detail.subway_line_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setSubwayLineName(String subwayLineName) {
        this.subwayLineName = subwayLineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_detail.subway_station_id
     *
     * @return the value of house_detail.subway_station_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getSubwayStationId() {
        return subwayStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_detail.subway_station_id
     *
     * @param subwayStationId the value for house_detail.subway_station_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setSubwayStationId(Integer subwayStationId) {
        this.subwayStationId = subwayStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_detail.subway_station_name
     *
     * @return the value of house_detail.subway_station_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getSubwayStationName() {
        return subwayStationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_detail.subway_station_name
     *
     * @param subwayStationName the value for house_detail.subway_station_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setSubwayStationName(String subwayStationName) {
        this.subwayStationName = subwayStationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_detail.house_id
     *
     * @return the value of house_detail.house_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_detail.house_id
     *
     * @param houseId the value for house_detail.house_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setHouseId(Integer houseId) {
        this.houseId = houseId;
    }
}