package com.zxf.DO;

public class SubwayStation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subway_station.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subway_station.subway_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer subwayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subway_station.name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subway_station.id
     *
     * @return the value of subway_station.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subway_station.id
     *
     * @param id the value for subway_station.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subway_station.subway_id
     *
     * @return the value of subway_station.subway_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getSubwayId() {
        return subwayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subway_station.subway_id
     *
     * @param subwayId the value for subway_station.subway_id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setSubwayId(Integer subwayId) {
        this.subwayId = subwayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subway_station.name
     *
     * @return the value of subway_station.name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subway_station.name
     *
     * @param name the value for subway_station.name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}