package com.zxf.DO;

public class Subway {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subway.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subway.name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subway.city_en_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String cityEnName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subway.id
     *
     * @return the value of subway.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subway.id
     *
     * @param id the value for subway.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subway.name
     *
     * @return the value of subway.name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subway.name
     *
     * @param name the value for subway.name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subway.city_en_name
     *
     * @return the value of subway.city_en_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getCityEnName() {
        return cityEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subway.city_en_name
     *
     * @param cityEnName the value for subway.city_en_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setCityEnName(String cityEnName) {
        this.cityEnName = cityEnName;
    }
}