package com.zxf.DO;

public class SupportAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column support_address.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column support_address.belong_to
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String belongTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column support_address.en_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String enName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column support_address.cn_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String cnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column support_address.level
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column support_address.baidu_map_lng
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Double baiduMapLng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column support_address.baidu_map_lat
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    private Double baiduMapLat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column support_address.id
     *
     * @return the value of support_address.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column support_address.id
     *
     * @param id the value for support_address.id
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column support_address.belong_to
     *
     * @return the value of support_address.belong_to
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getBelongTo() {
        return belongTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column support_address.belong_to
     *
     * @param belongTo the value for support_address.belong_to
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setBelongTo(String belongTo) {
        this.belongTo = belongTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column support_address.en_name
     *
     * @return the value of support_address.en_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column support_address.en_name
     *
     * @param enName the value for support_address.en_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setEnName(String enName) {
        this.enName = enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column support_address.cn_name
     *
     * @return the value of support_address.cn_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getCnName() {
        return cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column support_address.cn_name
     *
     * @param cnName the value for support_address.cn_name
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setCnName(String cnName) {
        this.cnName = cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column support_address.level
     *
     * @return the value of support_address.level
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column support_address.level
     *
     * @param level the value for support_address.level
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column support_address.baidu_map_lng
     *
     * @return the value of support_address.baidu_map_lng
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Double getBaiduMapLng() {
        return baiduMapLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column support_address.baidu_map_lng
     *
     * @param baiduMapLng the value for support_address.baidu_map_lng
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setBaiduMapLng(Double baiduMapLng) {
        this.baiduMapLng = baiduMapLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column support_address.baidu_map_lat
     *
     * @return the value of support_address.baidu_map_lat
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public Double getBaiduMapLat() {
        return baiduMapLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column support_address.baidu_map_lat
     *
     * @param baiduMapLat the value for support_address.baidu_map_lat
     *
     * @mbggenerated Fri Apr 03 15:49:55 CST 2020
     */
    public void setBaiduMapLat(Double baiduMapLat) {
        this.baiduMapLat = baiduMapLat;
    }
}